M48
; DRILL file {KiCad (7.0.0)} date Sun Oct  1 16:50:46 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-10-01T16:50:46+07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(7.0.0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1260
%
G90
G05
T1
X1.4803Y-1.8547
X1.4803Y-2.0823
T2
X1.3484Y-1.3484
X1.3484Y-2.5886
X2.7854Y-0.7874
X2.7854Y-2.5886
T0
M30
